############################
## CHANGE THESE
############################

baseURL: 'https://deabllaca.github.io/'
title: 'Dea Bllaca'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true


